"""
Pixeltable UDF for converting media file URLs to servable HTTP URLs.

This module provides a UDF that converts URLs in media columns (image/video/audio fileuri/fileurl)
to servable HTTP URLs. It looks at media destination settings for the column
and finds the appropriate client in the environment.
"""

from pixeltable import exceptions as excs
from pixeltable.func.udf import udf
from pixeltable.utils.code import local_public_names
from pixeltable.utils.object_stores import ObjectOps, ObjectPath, StorageTarget


@udf(is_method=True)
def servable_url(url: str, expiration_seconds: int) -> str:
    """
    Convert media columns stored blob URL to a servable HTTP presigned URL.

    This function infers the storage type from the URL and generates a servable presigned URL
    that can be used to access the media file via HTTP.

    This function uses presigned URLs from storage providers as the underlying mechanism. All limitations
    and conditions imposed by the storage provider on presigned URLs apply to the URLs generated by this
    function. For example:
    - Google Cloud Storage has a maximum expiration time of 7 days for presigned URLs
    - AWS S3 presigned URLs require proper region configuration
    - Azure SAS tokens are subject to storage account access policies
    - Each provider may have different expiration limits, signature requirements, and access restrictions

    Args:
        url: The media file URL (e.g., s3://bucket/path, gs://bucket/path, azure://container/path, file://path)
        expiration_seconds: Time in seconds for the servable URL to remain valid.

    Returns:
        A servable HTTP URL that can be used to access the media file.

    Examples:
        >>> tbl = pxt.get_table('my_table')
        >>> tbl.select(tbl.image_url, tbl.image_url.servable_url(3600)).collect()
    """
    if not url:
        return url

    # Parse the object storage address from the URL
    soa = ObjectPath.parse_object_storage_addr(url, allow_obj_name=True)

    # Only truly public HTTP/HTTPS URLs (HTTP_STORE) are already servable
    if soa.storage_target == StorageTarget.HTTP_STORE:
        return url

    # For file:// URLs, we can't generate servable URLs
    if soa.storage_target == StorageTarget.LOCAL_STORE:
        raise excs.Error(
            'Cannot generate servable URL for local file:// URLs. '
            'Please use cloud storage (S3, GCS, Azure) for servable URLs.'
        )

    store = ObjectOps.get_store(soa, allow_obj_name=True)
    return store.create_presigned_url(soa, expiration_seconds)


__all__ = local_public_names(__name__)


def __dir__() -> list[str]:
    return __all__
