"""Cloud e2e test.

Covers the full hosted database lifecycle: create, probe, update-runtime, stop/start, delete.
SDK probes run inline after each major phase to cross-check state via the proxy.

The tests run in sequence against one hosted database and must stay on a single xdist worker;
they are deselected by default and from every CI tier via the cloud_e2e marker.

Run:
    PIXELTABLE_API_KEY=sk_... pytest tests/cloud/test_cli_e2e.py -v -s -m cloud_e2e

Required env:
    PIXELTABLE_API_KEY

Optional env:
    PIXELTABLE_API_URL        (default: https://dev-internal-api.pixeltable.com)
    PIXELTABLE_CLOUD_HOST     (default: dev.pxt.run)

Pass --keep-cloud-resources to leave the database in place after the run.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
import textwrap
import time
import uuid
from pathlib import Path
from typing import Iterator, NamedTuple

import pytest

# xdist_group keeps the whole sequence on one worker: the tests share a single hosted database and
# run in order
pytestmark = [pytest.mark.cloud_e2e, pytest.mark.xdist_group('cloud_e2e')]

_SAMPLE_APP = Path(__file__).parent / 'sample_app'

_ORG = 'pixeltable'

_API_KEY = os.environ.get('PIXELTABLE_API_KEY', '')
_API_URL = os.environ.get('PIXELTABLE_API_URL', 'https://dev-internal-api.pixeltable.com')
_CLOUD_HOST = os.environ.get('PIXELTABLE_CLOUD_HOST', 'dev.pxt.run')


# ── helpers ──────────────────────────────────────────────────────────────────


def _cloud_env() -> dict[str, str]:
    e = os.environ.copy()
    e['PIXELTABLE_API_KEY'] = _API_KEY
    e['PIXELTABLE_API_URL'] = _API_URL
    e['PIXELTABLE_CLOUD_HOST'] = _CLOUD_HOST
    return e


def _pxt(*args: str, cwd: Path | None = None, check: bool = True, timeout: int = 900) -> str:
    r = subprocess.run(
        ['pxt', *args], capture_output=True, text=True, env=_cloud_env(), cwd=cwd, timeout=timeout, check=False
    )
    out = r.stdout + r.stderr
    if check and r.returncode != 0:
        raise AssertionError(f'pxt {" ".join(args)} failed (rc={r.returncode}):\n{out}')
    return out


def _pxt_json(*args: str, cwd: Path | None = None) -> str:
    return _pxt(*args, '--json', cwd=cwd)


def _sdk(code: str) -> str:
    """Run a Python snippet in a subprocess with cloud env."""
    r = subprocess.run(
        [sys.executable, '-c', textwrap.dedent(code)],
        capture_output=True,
        text=True,
        env=_cloud_env(),
        timeout=120,
        check=False,
    )
    return r.stdout + r.stderr


# ── resources fixture ─────────────────────────────────────────────────────────


class Resources(NamedTuple):
    org: str
    db: str
    db_uri: str
    table_uri: str  # pxt://org:db/e2e_items


@pytest.fixture(scope='module', autouse=True)
def require_api_key() -> None:
    """Skip every test in this module unless a key for the hosted deployment is available."""
    if _API_KEY == '':
        pytest.skip('PIXELTABLE_API_KEY not set')


@pytest.fixture(scope='module')
def resources(request: pytest.FixtureRequest) -> Iterator[Resources]:
    # A daemon left over from an earlier session holds the api url and cloud host it started with, so
    # restart it to pick up the values in _cloud_env()
    subprocess.run(['pxt', 'daemon', 'restart'], capture_output=True, env=_cloud_env(), check=False)

    # The sample app's uv.lock is gitignored and is never generated by the bundle build (that only packages
    # an existing lock). Regenerate it fresh from the pyproject on every run, always, even if one exists,
    # so a stale/absent lock can't deploy the wrong pixeltable or fail the server-side `uv sync --frozen`.
    (_SAMPLE_APP / 'uv.lock').unlink(missing_ok=True)
    lock = subprocess.run(['uv', 'lock'], cwd=_SAMPLE_APP, capture_output=True, text=True, check=False)
    if lock.returncode != 0:
        raise RuntimeError(f'uv lock failed for sample app:\n{lock.stdout}\n{lock.stderr}')

    run_id = uuid.uuid4().hex[:8]
    db = f'clitest-e2e-{run_id}'
    db_uri = f'pxt://{_ORG}:{db}'
    table_uri = f'{db_uri}/e2e_items'

    r = Resources(org=_ORG, db=db, db_uri=db_uri, table_uri=table_uri)
    try:
        yield r
    finally:
        if request.config.getoption('--keep-cloud-resources') or request.session.testsfailed > 0:
            print(f'\n[cleanup skipped, resources left for inspection: {db_uri}]', flush=True)
        else:
            _pxt('db', 'delete', db_uri, '--json', check=False)


# ── tests ─────────────────────────────────────────────────────────────────────


class TestCloudE2E:
    def test_org_list(self, resources: Resources) -> None:
        out = _pxt_json('org', 'list')
        assert resources.org in out

    def test_org_status(self, resources: Resources) -> None:
        out = _pxt_json('org', 'status', f'pxt://{resources.org}')
        assert resources.org in out

    def test_db_create(self, resources: Resources) -> None:
        _pxt('db', 'create', resources.db_uri)
        out = _pxt_json('db', 'status', resources.db_uri)
        assert 'AVAILABLE' in out
        assert resources.db in out

    def test_db_list(self, resources: Resources) -> None:
        out = _pxt_json('db', 'list', f'pxt://{resources.org}')
        assert resources.db in out

    def test_db_status(self, resources: Resources) -> None:
        out = _pxt_json('db', 'status', resources.db_uri)
        assert resources.db in out

    def test_db_update(self, resources: Resources) -> None:
        _pxt('db', 'update', resources.db_uri, '--workers', '2')
        out = _pxt_json('db', 'status', resources.db_uri)
        assert resources.db in out

    def test_sdk_create_table(self, resources: Resources) -> None:
        code = f"""
            import pixeltable as pxt
            pxt.init()
            t = pxt.create_table(
                '{resources.table_uri}',
                {{'id': pxt.Int, 'name': pxt.String}},
                primary_key='id',
                if_exists='ignore',
            )
            t.add_computed_column(name_upper=t.name.upper(), if_exists='ignore')
            status = t.insert([{{'id': i, 'name': f'item_{{i}}'}} for i in range(5)])
            print('rows:', status.num_rows)
        """
        # Retry: proxy gateway may lag behind AVAILABLE state
        for attempt in range(4):
            out = _sdk(code)
            if 'rows: 5' in out:
                break
            if attempt < 3:
                time.sleep(20)
        assert 'rows: 5' in out, f'SDK table create failed:\n{out}'

    def test_sdk_list_tables(self, resources: Resources) -> None:
        code = f"""
            import pixeltable as pxt
            pxt.init()
            tables = pxt.list_tables('{resources.db_uri}')
            print('tables:', [t for t in tables])
        """
        out = _sdk(code)
        assert 'e2e_items' in out, f'list_tables did not show e2e_items:\n{out}'

    def test_sdk_table_count(self, resources: Resources) -> None:
        code = f"""
            import pixeltable as pxt
            pxt.init()
            t = pxt.get_table('{resources.table_uri}')
            print('count:', t.count())
        """
        out = _sdk(code)
        assert 'count: 5' in out, f'table count wrong:\n{out}'

    def test_sdk_read_rows(self, resources: Resources) -> None:
        code = f"""
            import pixeltable as pxt
            pxt.init()
            t = pxt.get_table('{resources.table_uri}')
            rows = t.select(t.id, t.name).order_by(t.id).collect()
            for r in rows:
                print(r['id'], r['name'])
        """
        out = _sdk(code)
        for i in range(5):
            assert f'{i} item_{i}' in out, f'row {i} missing:\n{out}'

    def test_sdk_media_over_tunnel(self, resources: Resources) -> None:
        """Image round-trip over the TLS tunnel: insert a generated image, then read it back.

        Reading the image cell forces TunnelTransport.fetch() to pull /media/<ref> over the tunnel
        (the daemon serves it there, not via a direct HTTP GET). Regression guard for the media-localization
        gap where the tunnel transport produced no media_url and any media result would fail to localize.
        """
        media_uri = f'{resources.db_uri}/media_test'
        code = f"""
            import pixeltable as pxt
            from PIL import Image
            pxt.init()
            t = pxt.create_table(
                '{media_uri}',
                {{'id': pxt.Int, 'img': pxt.Image}},
                primary_key='id',
                if_exists='replace_force',
            )
            t.insert([{{'id': 1, 'img': Image.new('RGB', (64, 48), (255, 0, 0))}}])
            row = t.select(t.img).collect()[0]
            print('img_size:', row['img'].size)
        """
        # Retry: proxy gateway may lag behind AVAILABLE state
        for attempt in range(4):
            out = _sdk(code)
            if 'img_size: (64, 48)' in out:
                break
            if attempt < 3:
                time.sleep(20)
        assert 'img_size: (64, 48)' in out, f'media-over-tunnel round-trip failed:\n{out}'

    def test_sdk_concurrent_inserts(self, resources: Resources) -> None:
        """Two threads insert into the same hosted table at once, exercising the tunnel connection pool.

        The pre-pool single-connection client would interleave bytes on one socket and corrupt the stream;
        with the pool each thread borrows its own tunnel connection and both inserts land.
        """
        conc_uri = f'{resources.db_uri}/concurrent_test'
        code = f"""
            import concurrent.futures
            import pixeltable as pxt
            pxt.init()
            pxt.create_table(
                '{conc_uri}',
                {{'id': pxt.Int, 'name': pxt.String}},
                primary_key='id',
                if_exists='replace_force',
            )
            def _insert(base):
                t = pxt.get_table('{conc_uri}')
                return t.insert([{{'id': base + i, 'name': f'n{{base + i}}'}} for i in range(10)]).num_rows
            with concurrent.futures.ThreadPoolExecutor(max_workers=2) as ex:
                inserted = sum(ex.map(_insert, [0, 100]))
            print('inserted:', inserted)
            print('count:', pxt.get_table('{conc_uri}').count())
        """
        # Retry: proxy gateway may lag behind AVAILABLE state
        for attempt in range(4):
            out = _sdk(code)
            if 'count: 20' in out:
                break
            if attempt < 3:
                time.sleep(20)
        assert 'inserted: 20' in out, f'concurrent inserts did not all land:\n{out}'
        assert 'count: 20' in out, f'concurrent-insert final count wrong:\n{out}'

    def test_db_update_runtime(self, resources: Resources) -> None:
        out = _pxt('db', 'update-runtime', resources.db_uri, '--json', cwd=_SAMPLE_APP, timeout=1200)
        # stdout + stderr are combined by _pxt; find the JSON line (starts with '{')
        json_line = next((line for line in out.splitlines() if line.startswith('{')), None)
        assert json_line is not None, f'No JSON in update-runtime output:\n{out}'
        data = json.loads(json_line)
        assert data.get('state') == 'AVAILABLE', f'update-runtime did not return AVAILABLE:\n{out}'
        # update-runtime output may not include last_build_state; always verify via db status
        status_out = _pxt_json('db', 'status', resources.db_uri)
        status = json.loads(status_out)
        assert status.get('last_build_state') == 'ACTIVE', (
            f'Runtime build did not succeed (last_build_state={status.get("last_build_state")!r}, '
            f'error={status.get("last_build_error")!r})'
        )

    def test_db_stop(self, resources: Resources) -> None:
        out = _pxt_json('db', 'stop', resources.db_uri)
        assert 'STOPPED' in out

    def test_db_status_stopped(self, resources: Resources) -> None:
        out = _pxt_json('db', 'status', resources.db_uri)
        assert 'STOPPED' in out

    def test_db_start(self, resources: Resources) -> None:
        out = _pxt_json('db', 'start', resources.db_uri)
        assert 'AVAILABLE' in out

    def test_sdk_persistence_after_restart(self, resources: Resources) -> None:
        code = f"""
            import pixeltable as pxt
            pxt.init()
            t = pxt.get_table('{resources.table_uri}')
            all_ids = sorted(r['id'] for r in t.select(t.id).collect())
            print('orig_ok:', all(i in all_ids for i in range(5)))
            print('count:', len(all_ids))
        """
        out = _sdk(code)
        assert 'orig_ok: True' in out, f'original rows missing after restart:\n{out}'
        assert 'count: 5' in out, f'unexpected row count after restart:\n{out}'

    def test_db_delete(self, resources: Resources) -> None:
        _pxt('db', 'delete', resources.db_uri, '--json')
