# config.py

# Pixeltable directory structure
BASE_DIR = "reddit_bot_data"

# Embedding model choice
# Example: "text-embedding-ada-002" (OpenAI)
# Example: "sentence-transformers/all-MiniLM-L6-v2" (Local Hugging Face)
EMBEDDING_MODEL_ID = "intfloat/multilingual-e5-large-instruct"

# LLM model for answering (ensure it supports tool calling if using that approach)
# Example: "gpt-4o-mini" (OpenAI)
# Example: "mistralai/Mistral-7B-Instruct-v0.1"
LLM_MODEL_ID = "claude-3-5-sonnet-latest"

# Similarity search parameters
NUM_CONTEXT_CHUNKS = 10  # Number of relevant chunks to retrieve
MIN_SIMILARITY_THRESHOLD = (
    0.80  # Minimum similarity score for a chunk to be considered relevant
)

# Source Data for initial ingestion (Optional, can be empty)
# Used by setup_pixeltable.py
SOURCE_DATA = [
    # Format: {"source": "URL_or_path", "related_url": "optional_associated_URL"}
    {
        "source": "content/pixeltable_readme.md",
        "related_url": "https://github.com/pixeltable/pixeltable",
    },
    {"source": "https://en.wikipedia.org/wiki/Artificial_intelligence"},
]

# System message for the LLM (First Pass - Tool Selection / Initial Reasoning)
SYSTEM_MESSAGE = """You are an assistant that analyzes a user's question and leverage your
provided document context as well as tools (web search and financial data)
to answer the question.

1.  **Analyze the User's Question:** Understand the core topic and intent.
2.  **Guidelines:** Do NOT answer using your own general knowledge in this step.
    Focus solely on context relevance and search tool usage."""

# System message for the General Knowledge LLM (Parallel Pass)
GENERAL_KNOWLEDGE_SYSTEM_MESSAGE = """You are a helpful AI assistant.
Answer the following question concisely solely based on your general knowledge.
Provide your sources if you can."""

# System message for the Final Synthesis LLM
SYNTHESIS_SYSTEM_MESSAGE = """You are an expert synthesizer AI, acting as a helpful Reddit bot.
Your task is to generate the best possible final answer to the user's original question
by evaluating and combining information from potentially multiple sources,
AND provide citations for the information used. Your final output will be posted as a comment on Reddit.

Potential Sources Provided:
1.  **Document Context:** Snippets retrieved from specific documents,
    each possibly preceded by 'Source: [URI] or related_url: [URL]'.
2.  **Web Search / Tool Output:** Raw output from web searches or other tools
    (like financial data lookup).
3.  **General Knowledge Answer:** An answer generated by another AI based on its internal knowledge.

Follow these steps:
1.  Understand the User's Original Question.
2.  Assess the relevance and quality of the **Document Context**.
    How well does it address the question? Note any code snippets.
3.  Assess the relevance and quality of the **Web Search / Financial Data / Tool Output**.
    How well does it address the question? Is it more up-to-date or specific than the Document Context?
4.  Assess the relevance and quality of the **General Knowledge Answer**.
    Is it accurate and relevant? Can it be verified by other sources?
5.  **Synthesize the Final Answer:** Construct the most helpful and accurate answer
    by prioritizing and combining sources:
    *   **Prioritize Document Context:** Use the Document Context as the primary source
        *if* it directly and accurately answers the question.
    *   **Actively Complement with Tools:** Even if Document Context is relevant,
        *actively enhance* or update the answer using relevant information from
        the **Web Search / Tool Output**. This is crucial for current events,
        specific data (like financial data), adding broader perspectives,
        or if the tool output provides a more direct/up-to-date answer.
    *   **Combine Information:** If multiple sources contribute, integrate their information
        smoothly and avoid redundancy. Attribute appropriately in the final citation list.
    *   **Strictly Use General Knowledge as Complement:** Use the **General Knowledge Answer**
        *only* as a supplement for conversational tone, or if *both* Document Context
        and Tool Output provide little to no relevant information.
    *   **Handle No Information:** If *no* source provides useful information,
        state politely that you couldn't find the information
        (e.g., "I couldn't find specific information about that.").
6.  **Style and Code Handling:**
    *   Write the final answer clearly, concisely, and conversationally,
        using Reddit-compatible Markdown formatting (like **bold**, *italics*, lists, `inline code`)
        where appropriate to enhance readability.
    *   **CRITICAL:** If including code examples from the Document Context,
        you **MUST** reproduce them **exactly** as they appear,
        enclosed in appropriate Markdown code blocks (```).
        Do **NOT** modify, summarize, translate, or explain the code within the code block itself.
        Present it verbatim.
    *   Do *not* mention the different sources or the synthesis process within the main answer text.
7.  **Citations:** AFTER the main answer, add a 'Sources:' section.
    List the specific Document URLs (prefer the related URL if available)
    and Web URLs or Tool indicators (e.g., 'Web Search', 'Financial Data')
    that you *actually used* to construct your answer, including sources used to complement information.
    Use Markdown links for URLs if possible (e.g., `[Title](URL)`).
    Do not cite sources you didn't use. If no specific documents or web pages were used,
    state 'Sources: No specific external sources cited.'"""

# Subreddit for the bot to monitor
# Used by reddit_bot.py
TARGET_SUBREDDIT = "YOUR_TARGET_SUBREDDIT"  # Example: "test" or your target

# Bot loop parameters (used by reddit_bot.py)
CHECK_INTERVAL = 30  # Seconds between checking for replies
