name: Run the unit tests on PR or commit

on:
  pull_request:
    branches: [master]
  push:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        # Note: pixeltable currently fails on python 3.12.
        python-version: ["3.9", "3.10", "3.11"]
        poetry-version: ["1.7.1"]
        # Note: pixeltable currently fails on macos-latest (due to docker dependency).
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Define a venv cache
        uses: actions/cache@v3
        with:
          # The cache is keyed to the poetry.lock and related .toml files, so that
          # if the dependencies or poetry config change, the cache will be invalidated
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock', 'poetry.toml', 'pyproject.toml') }}
      - name: Install the project dependencies
        run: poetry install --with opt --with dev
      - name: Run the unit tests
        run: poetry run pytest -v
