name: tests

# On PR updates, the basic test configurations are run:
#   - Python 3.10 on ubuntu-24.04, macos-15, and windows-2022 runners.
#   - A minimal installation of Pixeltable (--no-dev) with Python 3.10 on ubuntu-24.04.
#   - Notebook tests.
#   - Linting, type-checking, docstring validation, etc.
#   - Random ops (for 30 minutes).
#
# In merge queue, all of the above configurations are run, and additionally:
#   - Python 3.14 on ubuntu-24.04, macos-15, and windows-2022 runners.
#   - Python 3.11, 3.12, and 3.13 on ubuntu-24.04.
#   - Minimal Pixeltable with Python 3.14 on ubuntu-24.04.
#   - Minimal Pixeltable with Python 3.10 on ubuntu-24.04-arm and macos-15-intel.
#
# On a weekly schedule, all of the above configurations are run (against branch 'main'), and additionally:
#   - Python 3.10 on ubuntu-t4 (equipped with an NVIDIA T4 GPU).
#
# A workflow_dispatch trigger will emulate the merge queue tests by default, but can be optionally
#     selected to run all configurations including ubuntu-t4.
#
# Github Actions secrets are unavailable on PRs; hence any tests that require API keys will be skipped.
# Secrets are available on all other triggers.

on:
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]
  schedule:
    - cron: "24 1 * * 2"  # Tuesday at 01:24 UTC
  workflow_dispatch:
    inputs:
      enable_tmate:
        type: boolean
        description: 'Enable SSH debugging with tmate'
        required: false
        default: false
      run_on_all_platforms:
        type: boolean
        description: 'Run on all platforms (including expensive ones)'
        required: false
        default: false

env:
  # PIXELTABLE_API_KEY: ${{ secrets.PIXELTABLE_API_KEY }}
  PIXELTABLE_B2_PROFILE: b2_profile
  PIXELTABLE_ENABLE_MPS: false  # Disable MPS on MacOS runners until/unless we find a way to cope with memory limits
  PIXELTABLE_R2_PROFILE: r2_profile
  PIXELTABLE_TIGRIS_PROFILE: tigris_profile
  PIXELTABLE_VERBOSITY: 0  # Suppress console output; we'll get log messages anyway when we need them
  PXTTEST_COCKROACH_DB_CONNECT_STR: ${{ secrets.PXTTEST_COCKROACH_DB_CONNECT_STR }}
  PXTTEST_COCKROACH_DB_ROOT_CERT: ${{ secrets.PXTTEST_COCKROACH_DB_ROOT_CERT }}
  PXTTEST_IN_CI: 1
  MINTLIFY_VERSION: 4.2.506
  NB_TEST_OPTS: ${{ (github.event_name == 'schedule' || inputs.run_on_all_platforms) && '--include-expensive' || '' }}
  UV_VERSION: 0.9.3
  HF_HUB_OFFLINE: 1

  # The llama-cpp-python build fails in CI with LLaVA support enabled. If we ever want to test specific LLaVA
  # functionality in CI, we'll need to investigate further (it's likely due to a missing compiler dependency).
  # We also disable Metal (GPU) support on MacOS, which doesn't seem to work properly in CI.
  CMAKE_ARGS: '-DLLAVA_BUILD=OFF -DGGML_METAL=OFF -DGGML_METAL_EMBED_LIBRARY=OFF'
  # This is required to build onnxsim on Ubuntu / Python 3.12+ configurations.
  CMAKE_POLICY_VERSION_MINIMUM: 3.5
  # This helps reduce memory pressure when loading models with transformers 5.2.0+.
  HF_DEACTIVATE_ASYNC_LOAD: 1

  # API keys for various services. In a PR, these secrets will be empty.
  ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_DEFAULT_REGION: us-west-2
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
  AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
  AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
  B2_ACCESS_KEY_ID: ${{ secrets.B2_ACCESS_KEY_ID }}
  B2_SECRET_ACCESS_KEY: ${{ secrets.B2_SECRET_ACCESS_KEY }}
  BEDROCK_API_KEY: ${{ secrets.BEDROCK_API_KEY }}
  BFL_API_KEY: ${{ secrets.BFL_API_KEY }}
  DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
  FAL_API_KEY: ${{ secrets.FAL_API_KEY }}
  FIREWORKS_API_KEY: ${{ secrets.FIREWORKS_API_KEY }}
  GCS_SERVICE_ACCOUNT_KEY: ${{ secrets.GCS_SERVICE_ACCOUNT_KEY }}
  GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
  GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
  GOOGLE_APPLICATION_CREDENTIALS: '/tmp/gcs-key.json'
  GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
  HF_AUTH_TOKEN: ${{ secrets.HF_AUTH_TOKEN }}
  JINA_API_KEY: ${{ secrets.JINA_API_KEY }}
  MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
  R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
  R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
  REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
  REVE_API_KEY: ${{ secrets.REVE_API_KEY }}
  RUNWAYML_API_SECRET: ${{ secrets.RUNWAYML_API_SECRET }}
  TIGRIS_ACCESS_KEY_ID: ${{ secrets.TIGRIS_ACCESS_KEY_ID }}
  TIGRIS_SECRET_ACCESS_KEY: ${{ secrets.TIGRIS_SECRET_ACCESS_KEY }}
  TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
  TWELVELABS_API_KEY: ${{ secrets.TWELVELABS_API_KEY }}
  VOYAGE_API_KEY: ${{ secrets.VOYAGE_API_KEY }}

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Install python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Generate test matrix
        id: set-matrix
        run: |
          ARGS=${{ github.event_name == 'workflow_dispatch' && inputs.run_on_all_platforms && '--force-all' || '' }}
          python tool/ci_tool.py generate-matrix "$GITHUB_OUTPUT" ${{ github.event_name }} $ARGS

  tests:
    name: ${{ matrix.display-name }}
    needs: generate-matrix
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}

    defaults:
      run:
        shell: bash -el {0}  # Needed for conda to work

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Set up tmate session
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.enable_tmate }}
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true
      - name: Google cloud auth
        if: ${{ env.GCS_SERVICE_ACCOUNT_KEY != '' }}
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ env.GCS_SERVICE_ACCOUNT_KEY }}
      - name: Delete unnecessary files
        if: ${{ !startsWith(matrix.os, 'windows') }}
        run: |
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo rm -rf /opt/hostedtoolcache
          df -h
      - name: Install miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          activate-environment: pxt
          conda-remove-defaults: true
      - name: Install python
        run: |
          ./scripts/retry.sh 3 30 conda install -y -c conda-forge python=${{ matrix.python-version }} pip
          conda info
      - name: Install tools and libraries
        # cmake is needed for certain CI environments where it is not preinstalled.
        run: ./scripts/retry.sh 3 30 conda install -y -c conda-forge 'cmake>=3.22' libiconv 'ffmpeg==6.1.1=gpl*'
      - name: Install ollama
        if: ${{ matrix.uv-options == '' && startsWith(matrix.os, 'ubuntu') && matrix.python-version == '3.10' }}
        run: |
          curl -fsSL https://ollama.com/install.sh | sh
          sleep 10  # Wait for the ollama server to start
          # Pull the models used for testing now, with retries, to safeguard against connection issues
          ./scripts/retry.sh 3 30 ollama pull 'qwen3:0.6b'
          ./scripts/retry.sh 3 30 ollama pull 'qwen3-embedding:0.6b'
      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          python -m pip install "uv==$UV_VERSION"
      - name: uv.lock check
        if: ${{ matrix.test-category == 'lint' }}
        run: uv lock --check
      - name: Define a venv cache
        uses: actions/cache@v4
        if: false
        with:
          # The cache is keyed to the following:
          # - Matrix parameters
          # - uv.lock and related .toml files and Makefile (so that if the
          #   dependencies or uv config change, the cache will be invalidated)
          path: ${{ env.CONDA }}/envs
          key: venv-${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.uv-options }}-${{
            hashFiles('.github/workflows/pytest.yml', 'uv.lock', 'pyproject.toml', 'Makefile') }}
      - name: Install the project dependencies
        # Retry 3 times to be resilient against transient connectivity issues.
        run: |
          export VIRTUAL_ENV="$CONDA_PREFIX"
          ./scripts/retry.sh 3 60 uv sync --active ${{ matrix.uv-options }}
      - name: Clean the uv cache
        run: uv cache clean
      - name: Set up credentials
        run: ./scripts/set-up-ci-credentials.sh
      - name: Download HF models for unit tests
        if: ${{ matrix.test-category == 'py' }}
        env:
          HF_HUB_OFFLINE: 0
        run: |
          ./scripts/retry.sh 5 60 hf download intfloat/e5-large-v2 --revision f169b11e22de13617baa190a028a32f3493550b6
          ./scripts/retry.sh 5 60 hf download facebook/detr-resnet-50 --revision 1d5f47bd3bdd2c4bbfa585418ffe6da5028b4c0b
          ./scripts/retry.sh 5 60 hf download facebook/detr-resnet-50-panoptic --revision d53b52a799403a8867920f82c869e40732b47037
          ./scripts/retry.sh 5 60 hf download openai/clip-vit-base-patch32 --revision 3d74acf9a28c67741b2f4f2ea7635f0aaf6f0268
          ./scripts/retry.sh 5 60 hf download laion/CLIP-ViT-B-32-laion2B-s34B-b79K --revision 1a25a446712ba5ee05982a381eed697ef9b435cf
          ./scripts/retry.sh 5 60 hf download google/vit-base-patch16-224 --revision 3f49326eb077187dfe1c2a2bb15fbd74e6ab91e3
          ./scripts/retry.sh 5 60 hf download sentence-transformers/all-mpnet-base-v2 --revision e8c3b32edf5434bc2275fc9bab85f82640a19130
          ./scripts/retry.sh 5 60 hf download BAAI/bge-reranker-base --revision 2cfc18c9415c912f9d8155881c133215df768a70
          ./scripts/retry.sh 5 60 hf download cross-encoder/ms-marco-MiniLM-L-6-v2 --revision c5ee24cb16019beea0893ab7796b1df96625c6b8
          ./scripts/retry.sh 5 60 hf download cross-encoder/ms-marco-TinyBERT-L-2-v2 --revision 81d1926f67cb8eee2c2be17ca9f793c7c3bd20cc
          ./scripts/retry.sh 5 60 hf download facebook/s2t-small-librispeech-asr --revision 256e91a603c013ae09aa1e4c09cfc3f8acdf8d19
          ./scripts/retry.sh 5 60 hf download facebook/s2t-medium-mustc-multilingual-st --revision 79cc4237d4495aea7863076900d2f23af77f3ddc
          ./scripts/retry.sh 5 60 hf download Qwen/Qwen3-0.6B --revision c1899de289a04d12100db370d81485cdf75e47ca
          ./scripts/retry.sh 5 60 hf download cardiffnlp/twitter-roberta-base-sentiment-latest --revision 3216a57f2a0d9c45a2e6c20157c20c49fb4bf9c7
          ./scripts/retry.sh 5 60 hf download Falconsai/text_summarization --revision 6e505f907968c4a9360773ff57885cdc6dca4bfd
          ./scripts/retry.sh 5 60 hf download distilbert/distilbert-base-cased-distilled-squad --revision 564e9b582944a57a3e586bbb98fd6f0a4118db7f
          ./scripts/retry.sh 5 60 hf download Helsinki-NLP/opus-mt-en-fr --revision dd7f6540a7a48a7f4db59e5c0b9c42c8eea67f18
          ./scripts/retry.sh 5 60 hf download dslim/bert-base-NER --revision d1a3e8f13f8c3566299d95fcfc9a8d2382a9affc
          ./scripts/retry.sh 5 60 hf download openai/whisper-tiny --revision 169d4a4341b33bc18d8881c4b69c2e104e1cc0af
          ./scripts/retry.sh 5 60 hf download microsoft/speecht5_tts --revision 30fcde30f19b87502b8435427b5f5068e401d5f6
          ./scripts/retry.sh 5 60 hf download microsoft/speecht5_hifigan --revision bb6f429406e86a9992357a972c0698b22043307d
          ./scripts/retry.sh 5 60 hf download Qwen/Qwen2-0.5B-Instruct-GGUF --revision 198f08841147e5196a6a69bd0053690fb1fd3857 --include '*q3_k_m.gguf'
          ./scripts/retry.sh 5 60 hf download --repo-type dataset Cohere/wikipedia-2023-11-embed-multilingual-v3 --revision ade45fb52bd549f5e8c065636fe4160a43c2af36 --include 'cr/*' --include 'mi/*'
      - name: Run the unit tests
        if: ${{ matrix.test-category == 'py' }}
        env:
          PXTTEST_CI_OS: ${{ matrix.os }}
        # Run the tests with the 'expensive' marker only once, on ubuntu-24.04 with Python 3.10. The other tests
        # (including tests with the 'remote_api' marker that are not also marked 'expensive') will run on all matrix
        # configurations.
        run: |
          echo 'Running tests with options: ${{ matrix.pytest-options }}'
          echo 'Extra pre-test command    : ${{ matrix.pre-test-cmd }}'
          ${{ matrix.pre-test-cmd }}
          coverage run -m --source=pixeltable pytest -v --strict-markers ${{ matrix.pytest-options }}
          coverage report -m
      - name: Download HF models for notebook tests
        if: ${{ matrix.test-category == 'ipynb' }}
        env:
          HF_HUB_OFFLINE: 0
        run: |
          ./scripts/retry.sh 5 60 hf download sentence-transformers/all-MiniLM-L6-v2 --revision 1110a243fdf4706b3f48f1d95db1a4f5529b4d41
          ./scripts/retry.sh 5 60 hf download sentence-transformers/all-MiniLM-L12-v2 --revision a50ef00143b4d5391434df20ae11632588ac25be
          ./scripts/retry.sh 5 60 hf download facebook/detr-resnet-50 --revision 1d5f47bd3bdd2c4bbfa585418ffe6da5028b4c0b
          ./scripts/retry.sh 5 60 hf download openai/clip-vit-base-patch32 --revision 3d74acf9a28c67741b2f4f2ea7635f0aaf6f0268
          ./scripts/retry.sh 5 60 hf download intfloat/e5-large-v2 --revision f169b11e22de13617baa190a028a32f3493550b6
          ./scripts/retry.sh 5 60 hf download Qwen/Qwen2.5-0.5B-Instruct-GGUF --revision 9217f5db79a29953eb74d5343926648285ec7e67 --include '*q5_k_m.gguf'
          ./scripts/retry.sh 5 60 hf download bartowski/Llama-3.2-1B-Instruct-GGUF --revision 067b946cf014b7c697f3654f621d577a3e3afd1c --include '*Q5_K_M.gguf'
          ./scripts/retry.sh 5 60 hf download --repo-type dataset cornell-movie-review-data/rotten_tomatoes --revision aa13bc287fa6fcab6daf52f0dfb9994269ffea28
          ./scripts/retry.sh 5 60 hf download --repo-type dataset stanfordnlp/imdb --revision e6281661ce1c48d982bc483cf8a173c1bbeb5d31
          ./scripts/retry.sh 5 60 hf download --repo-type dataset ylecun/mnist --revision 77f3279092a1c1579b2250db8eafed0ad422088c
      - name: Run the notebook tests
        if: ${{ matrix.test-category == 'ipynb' }}
        run: |
          ./scripts/prepare-nb-tests.sh --no-pip $NB_TEST_OPTS tests/target/nb-tests docs/release tests
          set +e  # don't exit immediately on error, so that we can retry
          pytest -v -m '' --nbmake --nbmake-timeout=1800 tests/target/nb-tests/*.ipynb
          pytest -v -m '' --nbmake --nbmake-timeout=1800 --lf --lfnf=none  # retry failed tests once
          if [[ $? != 0 && $? != 5 ]]; then  # exit code 5 = no tests collected on 2nd run
            exit 1
          fi
      - name: Run stress tests
        if: ${{ matrix.test-category == 'random-ops' }}
        run: ./scripts/stress-tests.sh 12 360
      - name: Type check
        if: ${{ matrix.test-category == 'lint' }}
        run: mypy pixeltable tests tool
      - name: Validate docstrings
        if: ${{ matrix.test-category == 'lint' }}
        run: |
          # Install quarto and mintlify in order to build the docs
          conda install -y -c conda-forge quarto nodejs
          npm install -g mint@$MINTLIFY_VERSION
          python -m pixeltable_doctools.build
          cd target/docs && mint broken-links
      - name: Lint
        if: ${{ matrix.test-category == 'lint' }}
        run: ruff check pixeltable tests tool
      - name: Formatter check
        if: ${{ matrix.test-category == 'lint' }}
        run: |
          ruff format --check
          ruff check --select I
      - name: Notebook checks
        if: ${{ matrix.test-category == 'lint' }}
        run: ./scripts/check-notebooks.sh
      - name: Archive log files
        # Archive the log files even if a preceding step failed. Currently we do this only on ubuntu runners.
        if: ${{ always() && startsWith(matrix.os, 'ubuntu') }}
        uses: actions/upload-artifact@v4
        with:
          name: pixeltable-pytest-logs-${{ matrix.display-name }}-${{ matrix.os }}-${{ matrix.python-version }}
          path: /tmp/pytest-of-runner/pytest-0/base0/.pixeltable/logs
      - name: Print utilization info
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: |
          df -h
          du -h -d3 /home/runner || true
          du -h -d3 /home/runner/.cache || true
      - name: Print utilization info
        if: ${{ !startsWith(matrix.os, 'ubuntu') }}
        run: df -h

  validate:
    needs: tests
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Fail on error
        run: exit 1
